module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Vendors", [
      {
        category: "Catering",
        vendor_name: "Olive Garden",
        contact_name: "Luigi",
        address: "123 Somewhere St., Plano, TX 75222",
        phone_number: "214-512-3142",
        email: "olive@olivegarden.com",
        projected_cost: 1200,
        actual_cost: 1350,
        contract: "contract.pdf",
        notes: "Salad, Chicken Alfredo, and Spaghetti is all we would get!!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Catering",
        vendor_name: "Austin's Barbeque",
        contact_name: "Austin",
        address: "123 Anywhere St., Plano, TX 75222",
        phone_number: "903-434-2152",
        email: "austin@austinbbq.com",
        projected_cost: 900,
        actual_cost: 1050,
        contract: "contract.pdf",
        notes:
          "Brisket, Pulled Pork, Potatoe Salad, and Baked Beans would be our choices",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Catering",
        vendor_name: "New Catering",
        contact_name: "Joe",
        address: "12 Anywhere St., Plano, TX 75222",
        phone_number: "817-434-2152",
        email: "jose@austinbbq.com",
        projected_cost: 900,
        actual_cost: 1050,
        contract: "contract.pdf",
        notes:
          "Brisket, Pulled Pork, Potatoe Salad, and Baked Beans would be our choices",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Catering",
        vendor_name: "Blah Blah Catering",
        contact_name: "Austin",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "903-123-2152",
        email: "jane@austinbbq.com",
        projected_cost: 900,
        actual_cost: 1050,
        contract: "contract.pdf",
        notes:
          "Brisket, Pulled Pork, Potatoe Salad, and Baked Beans would be our choices",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Venue",
        vendor_name: "Plano Event Center",
        contact_name: "Janet Murphy",
        address: "555 Downwhere St., Plano, TX 75222",
        phone_number: "972-941-5840",
        email: "planoeventcenter@plano.gov",
        projected_cost: 18000,
        actual_cost: 22000,
        contract: "contract.pdf",
        notes: "Love the layout and includes Security, Valet Parking.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Florist",
        vendor_name: "Floral Moral in Plano",
        contact_name: "Billy",
        address: "3333 Butwhere St., Plano, TX 75222",
        phone_number: "972-959-2152",
        email: "billy@floralmoral.com",
        projected_cost: 700,
        actual_cost: 679,
        contract: "contract.pdf",
        notes:
          "These guys can provide orchids, bouquets, and floral arrangment for church.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Venue",
        vendor_name: "First Baptist Church of Plano",
        contact_name: "Ethel Mertz",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Vendors", null, {});
  },
};
