module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Vendors", [
      {
        category: "Catering",
        vendor_name: "Olive Garden",
        contact_name: "Luigi",
        address: "123 Somewhere St., Plano, TX 75222",
        phone_number: "214-512-3142",
        email: "olive@olivegarden.com",
        projected_cost: 1200,
        actual_cost: 1350,
        contract: "contract.pdf",
        notes: "Salad, Chicken Alfredo, and Spaghetti is all we would get!!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Catering",
        vendor_name: "Austin's Barbeque",
        contact_name: "Austin",
        address: "123 Anywhere St., Plano, TX 75222",
        phone_number: "903-434-2152",
        email: "austin@austinbbq.com",
        projected_cost: 900,
        actual_cost: 1050,
        contract: "contract.pdf",
        notes:
          "Brisket, Pulled Pork, Potatoe Salad, and Baked Beans would be our choices",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Catering",
        vendor_name: "New Catering",
        contact_name: "Joe",
        address: "12 Anywhere St., Plano, TX 75222",
        phone_number: "817-434-2152",
        email: "jose1@austinbbq.com",
        projected_cost: 900,
        actual_cost: 1050,
        contract: "contract.pdf",
        notes:
          "Brisket, Pulled Pork, Potatoe Salad, and Baked Beans would be our choices",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Catering",
        vendor_name: "Pho Sho Catering",
        contact_name: "Austin",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "903-123-2152",
        email: "jane2@austinbbq.com",
        projected_cost: 900,
        actual_cost: 1050,
        contract: "contract.pdf",
        notes:
          "Brisket, Pulled Pork, Potatoe Salad, and Baked Beans would be our choices",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Venue",
        vendor_name: "Dallas Event Center",
        contact_name: "Craig Spence",
        address: "555 Gatsby St., Plano, TX 75222",
        phone_number: "972-222-5840",
        email: "dallaseventcenter4@dddwd.gov",
        projected_cost: 18000,
        actual_cost: 22000,
        contract: "contract.pdf",
        notes: "Too big and doesn't includes Security or Valet Parking.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Venue",
        vendor_name: "Plano Event Center",
        contact_name: "Janet Murphy",
        address: "555 Downwhere St., Plano, TX 75222",
        phone_number: "972-941-5840",
        email: "planoeventcenter4@plano.gov",
        projected_cost: 18000,
        actual_cost: 22000,
        contract: "contract.pdf",
        notes: "Love the layout and includes Security, Valet Parking.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Venue",
        vendor_name: "Plano Event Center",
        contact_name: "Janet Murphy",
        address: "555 Downwhere St., Plano, TX 75222",
        phone_number: "972-941-5840",
        email: "planoevent3@plano.gov",
        projected_cost: 18000,
        actual_cost: 22000,
        contract: "contract.pdf",
        notes: "Love the layout and includes Security, Valet Parking.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Venue",
        vendor_name: "Dallas Event Center",
        contact_name: "Craig Spence",
        address: "555 Gatsby St., Plano, TX 75222",
        phone_number: "972-222-5840",
        email: "dallaseventcente4@dddwd.gov",
        projected_cost: 18000,
        actual_cost: 22000,
        contract: "contract.pdf",
        notes: "Too big and doesn't includes Security or Valet Parking.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Venue",
        vendor_name: "Plano Event Center",
        contact_name: "Janet Murphy",
        address: "555 Downwhere St., Plano, TX 75222",
        phone_number: "972-941-5840",
        email: "planocenter2@plano.gov",
        projected_cost: 18000,
        actual_cost: 22000,
        contract: "contract.pdf",
        notes: "Love the layout and includes Security, Valet Parking.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Venue",
        vendor_name: "Plano Event Center",
        contact_name: "Janet Murphy",
        address: "555 Downwhere St., Plano, TX 75222",
        phone_number: "972-941-5840",
        email: "eventcenter4@plano.gov",
        projected_cost: 18000,
        actual_cost: 22000,
        contract: "contract.pdf",
        notes: "Love the layout and includes Security, Valet Parking.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Florist",
        vendor_name: "Floral Moral in Plano",
        contact_name: "Billy",
        address: "3333 Butwhere St., Plano, TX 75222",
        phone_number: "972-959-2152",
        email: "billy43@floralmoral.com",
        projected_cost: 700,
        actual_cost: 679,
        contract: "contract.pdf",
        notes:
          "These guys can provide orchids, bouquets, and floral arrangment for church.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Florist",
        vendor_name: "Floral Moral in Plano",
        contact_name: "Billy",
        address: "3333 Butwhere St., Plano, TX 75222",
        phone_number: "972-959-2152",
        email: "billy2@floralmoral.com",
        projected_cost: 700,
        actual_cost: 679,
        contract: "contract.pdf",
        notes:
          "These guys can provide orchids, bouquets, and floral arrangment for church.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Florist",
        vendor_name: "Floral Moral in Plano",
        contact_name: "Billy",
        address: "3333 Butwhere St., Plano, TX 75222",
        phone_number: "972-959-2152",
        email: "billy3@floralmoral.com",
        projected_cost: 700,
        actual_cost: 679,
        contract: "contract.pdf",
        notes:
          "These guys can provide orchids, bouquets, and floral arrangment for church.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Florist",
        vendor_name: "Floral Moral in Plano",
        contact_name: "Billy",
        address: "3333 Butwhere St., Plano, TX 75222",
        phone_number: "972-959-2152",
        email: "billy4@floralmoral.com",
        projected_cost: 700,
        actual_cost: 679,
        contract: "contract.pdf",
        notes:
          "These guys can provide orchids, bouquets, and floral arrangment for church.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Venue",
        vendor_name: "First Baptist Church of Plano",
        contact_name: "Ethel Mertz",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Venue",
        vendor_name: "First Baptist Church of Plano",
        contact_name: "Ethel Mertz",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz1@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Venue",
        vendor_name: "First Baptist Church of Plano",
        contact_name: "Ethel Mertz",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz2@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 3,
      },
      {
        category: "Music",
        vendor_name: "Banda Zetta",
        contact_name: "Beto Guzman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz3@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 3,
      },
      {
        category: "Music",
        vendor_name: "Banda Zetta",
        contact_name: "Beto Guzman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz4@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Music",
        vendor_name: "DJ COVID-2020",
        contact_name: "DJ Sick",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "sickmusic@muzic.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "This Guy is AWESOME!!!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Music",
        vendor_name: "Piano Guy",
        contact_name: "John Witman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "john1@piano.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "Not Bad!!.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Music",
        vendor_name: "Banda Zetta",
        contact_name: "Beto Guzman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz8@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Music",
        vendor_name: "DJ COVID-2020",
        contact_name: "DJ Sick",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "sickmusic1@muzic.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "This Guy is AWESOME!!!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Music",
        vendor_name: "Piano Guy",
        contact_name: "John Witman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "john6@piano.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "Not Bad!!.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Music",
        vendor_name: "Banda Zetta",
        contact_name: "Beto Guzman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "emertz9@firstbcp.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "We would have to take marital classes.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 3,
      },
      {
        category: "Music",
        vendor_name: "DJ COVID-2020",
        contact_name: "DJ Sick",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "sickmusic5@muzic.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "This Guy is AWESOME!!!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 3,
      },
      {
        category: "Music",
        vendor_name: "Piano Guy",
        contact_name: "John Witman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "john9@piano.com",
        projected_cost: 700,
        actual_cost: 875,
        contract: "contract.pdf",
        notes: "Not Bad!!.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 3,
      },
      {
        category: "Jeweler",
        vendor_name: "Zales",
        contact_name: "Billy Goodman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Billy00@jeweler.com",
        projected_cost: 6000,
        actual_cost: 5900,
        contract: "contract.pdf",
        notes: "Nice and has good clarity!!.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Jeweler",
        vendor_name: "Zales",
        contact_name: "Billy Goodman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Billy01@jeweler.com",
        projected_cost: 6000,
        actual_cost: 5900,
        contract: "contract.pdf",
        notes: "Nice and has good clarity!!.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Jeweler",
        vendor_name: "Zales",
        contact_name: "Billy Goodman",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Billy02@jeweler.com",
        projected_cost: 6000,
        actual_cost: 5900,
        contract: "contract.pdf",
        notes: "Nice and has good clarity!!.",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 3,
      },
      {
        category: "Rentals",
        vendor_name: "Tux's R US",
        contact_name: "Kelly",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Kelly@rentals.com",
        projected_cost: 300,
        actual_cost: 300,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Rentals",
        vendor_name: "Limo Service",
        contact_name: "Jenny",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Jenny34@limos.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Rentals",
        vendor_name: "Glass and Silverware R US",
        contact_name: "Jenny",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Jenny35@utils.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Rentals",
        vendor_name: "Linens by US",
        contact_name: "Susan",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "susan3@utils.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Rentals",
        vendor_name: "Chairs and Tables",
        contact_name: "Chow",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "chow@utils.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 1,
      },
      {
        category: "Rentals",
        vendor_name: "Tux's R US",
        contact_name: "Kelly",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Kelly38@rentals.com",
        projected_cost: 300,
        actual_cost: 300,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Rentals",
        vendor_name: "Limo Service",
        contact_name: "Jenny",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Jenny86@limos.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Rentals",
        vendor_name: "Glass and Silverware R US",
        contact_name: "Jenny",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "Jenny85@utils.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Rentals",
        vendor_name: "Linens by US",
        contact_name: "Susan",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "susan45@utils.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
      {
        category: "Rentals",
        vendor_name: "Chairs and Tables",
        contact_name: "Chow",
        address: "123 Nowhere St., Plano, TX 75222",
        phone_number: "972-525-1122",
        email: "chow3@utils.com",
        projected_cost: 700,
        actual_cost: 700,
        contract: "contract.pdf",
        notes: "Got it!",
        createdAt: new Date(),
        updatedAt: new Date(),
        event_id: 2,
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Vendors", null, {});
  },
};
